#spring:
#  jpa:
#    hibernate:
#      ddl-auto: none
  thymeleaf:
    cache: false

    spring:
      datasource:
        platform: postgresql
        url: jdbc:postgresql://ec2-54-243-202-113.compute-1.amazonaws.com:5432/d5d64qbbr1qkdd
        username: jqdpbetabrzpah
        password: ncDc-pk2zGd300DtotoiLeRa0M
        driverClassName: org.postgresql.Driver


      jpa:
        database: POSTGRESQL
        database-platform: org.hibernate.dialect.PostgreSQL9Dialect